version: '3.8'

services:
  app:
    build: .
    container_name: faq_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/faq_system
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - faq_network

  mongo:
    image: mongo:latest
    container_name: faq_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - faq_network

  redis:
    image: redis:alpine
    container_name: faq_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - faq_network

volumes:
  mongodb_data:

networks:
  faq_network:
    driver: bridge
